name: build

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: image
      uses: redhat-actions/buildah-build@v2
      id: build-image
      with:
        image: test
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Containerfile
