name: test
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  test:
    name: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false
      - name: Install deps
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      - name: Install envtest
        run: go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
      - name: Run Ginkgo Tests
        run: "make test"
